# Generated by Django 2.2.2 on 2019-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='picture',
            field=models.ImageField(null=True, upload_to='gallery/media/images/'),
        ),
    ]
